

admin_default:
   path: /
   methods: GET
   controller: App\Controller\Admin\DefaultController::index

admin_index:
   path: /admin
   methods: GET
   controller: App\Controller\Admin\DefaultController::index

product_index:
   path: /admin/product
   methods: GET
   controller: App\Controller\Admin\ProductController::index


product_new:
   path: /admin/product/new
   methods: ["GET","POST"]
   controller: App\Controller\Admin\ProductController::new

product_edit:
   path: /admin/product/{id}/edit
   methods: ["GET","POST"]
   controller: App\Controller\Admin\ProductController::edit


product_show:
   path: /admin/product/{id}
   methods: GET
   controller: App\Controller\Admin\ProductController::show

product_delete:
   path: /admin/product/{id}
   methods: DELETE
   controller: App\Controller\Admin\ProductController::delete


app_login:
   path: /admin/login
   methods:  ["GET","POST"]
   controller: App\Controller\SecurityController::login

app_logout:
   path: /admin/logout
   methods:  GET
   controller: App\Controller\SecurityController::logout


app_register:
   path: /admin/register
   methods:  ["GET","POST"]
   controller: App\Controller\RegistrationController::register

